TOPDIR = ..

ASCIIDOC = osmohlr-usermanual.adoc
ASCIIDOC_DEPS = chapters/*.adoc *.vty *.ctrl
include $(TOPDIR)/build/Makefile.asciidoc.inc

VTY_REFERENCE = osmohlr-vty-reference.xml
include $(TOPDIR)/build/Makefile.vty-reference.inc

include $(TOPDIR)/build/Makefile.common.inc
